### ISSUE TITLE
IOS16注入不了

### ISSUE THREAD

**Issue by lsdlh** [Nice-PLQ/devtools-remote-debugger#10]
<script src="http://192.168.1.151:8080/remote/debug/dist/page/sdk.js" crossorigin="anonymous"></script>请求好像会直接被屏蔽，抓包抓不到js请求，测试安卓可以抓到可以注入

**Comment by nsear** [comment]
> <script src="http://192.168.1.151:8080/remote/debug/dist/page/sdk.js" crossorigin="anonymous"></script>请求好像会直接被屏蔽，抓包抓不到js请求，测试安卓可以抓到可以注入

iOS 16.6 我试了下 Edge， Chrome 是能正常使用的，Safari的话提示了 “只支持Chrome/Edge浏览器进行调试”

**Comment by lsdlh** [comment]
> > <script src="http://192.168.1.151:8080/remote/debug/dist/page/sdk.js" crossorigin="anonymous"></script>请求好像会直接被屏蔽，抓包抓不到js请求，测试安卓可以抓到可以注入
> 
> iOS 16.6 我试了下 Edge， Chrome 是能正常使用的，Safari的话提示了 “只支持Chrome/Edge浏览器进行调试”

试的微信和Safari

**Comment by Nice-PLQ** [comment]
用ios16下的微信或safari里打开http://192.168.1.151:8080/remote/debug/dist/page/sdk.js，看看能不能正常访问

**Comment by lsdlh** [comment]
> 使用ios16下的微信或safari里打开[http://192.168.1.151:8080/remote/debug/dist/page/sdk.js，看看能否正常访问](http://192.168.1.151:8080/remote/debug/dist/page/sdk.js%EF%BC%8C%E7%9C%8B%E7%9C%8B%E8%83%BD%E4%B8%8D%E8%83%BD%E6%AD%A3%E5%B8%B8%E8%AE%BF%E9%97%AE) @lsdlh

可以

**Comment by lsdlh** [comment]
用https即可
