### ISSUE TITLE
大佬，我想把recorder的功能也加进来，能不能请教下，加入recorder要从哪着手

### ISSUE THREAD

**Issue by Fathands** [Nice-PLQ/devtools-remote-debugger#14]

**Comment by Nice-PLQ** [comment]
Performance里的recorder能力？这块应该不一定能实现

**Comment by Fathands** [comment]
> 

![image](https://github.com/Nice-PLQ/devtools-remote-debugger/assets/20460628/b65c449f-b0d0-444f-acbd-c678f9817556)
这块的recorder，但是现在点击创建新的recording无效，暂时还没找到原因，想请教大佬看下

**Comment by Fathands** [comment]
> Performance里的recorder能力？这块应该不一定能实现

![image](https://github.com/Nice-PLQ/devtools-remote-debugger/assets/20460628/533a2227-845c-40c7-8afd-31455a4a294a)
这一块的recorder，但是现在创建新的recording无效，想请教下大佬

**Comment by Nice-PLQ** [comment]
这个Recorder能力是没实现的

**Comment by Fathands** [comment]
> 这个Recorder能力是没实现的

想实现这个recorder ，请教大佬一下要从哪着手，感谢感谢~

**Comment by Nice-PLQ** [comment]
<img width="2593" alt="image" src="https://github.com/Nice-PLQ/devtools-remote-debugger/assets/10710341/6f52396a-4dd5-4c47-8b40-4abd84229f8b">

@Fathands 你可以先在devtools里的Protocol monitor看下Recorder能力会用到什么CDP协议，然后在去看CDP具体的协议规范，通过原生JavaScript去实现。

**Comment by Fathands** [comment]
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/10710341/266240026-6f52396a-4dd5-4c47-8b40-4abd84229f8b.png">
> @Fathands 你可以先在devtools里的Protocol monitor看下Recorder能力会用到什么CDP协议，然后在去看CDP具体的协议规范，通过原生JavaScript去实现。
> 
> Recorder貌似还是实验性的，用原生JavaScript实现难度应该会比较大

好的好的 多谢大佬~
