### ISSUE TITLE
nginx部署的静态页面怎么使用

### ISSUE THREAD

**Issue by layne0625** [Nice-PLQ/devtools-remote-debugger#16]
nginx部署的静态页面， 是加载sdk.js之后， 调试页面发起的websocket应该转发到node服务上吗？

**Comment by layne0625** [comment]
![image](https://github.com/Nice-PLQ/devtools-remote-debugger/assets/24985105/461e677c-4731-4699-8878-ab7d5f5b9274)

![image](https://github.com/Nice-PLQ/devtools-remote-debugger/assets/24985105/b1b52cc1-3b4f-4703-a50c-26238436e810)
可以跳转debug但是页面出来的是空白， 页面元素是有的，这是什么原因

**Comment by layne0625** [comment]
![image](https://github.com/Nice-PLQ/devtools-remote-debugger/assets/24985105/be3bdaa0-2747-4c0e-bf09-cdd05dad2c3d)
这样shi'yo使用不知道是不是有问题

**Comment by Nice-PLQ** [comment]
> ![image](https://user-images.githubusercontent.com/24985105/279556527-461e677c-4731-4699-8878-ab7d5f5b9274.png)
> 
> ![image](https://user-images.githubusercontent.com/24985105/279556341-b1b52cc1-3b4f-4703-a50c-26238436e810.png) 可以跳转debug但是页面出来的是空白， 页面元素是有的，这是什么原因

推荐用ScreenPreview进行页面预览，左边这个的预览原理是通过dom-to-image转成png图片进行显示的，更多的是作为实时预览的一个补充能力

**Comment by layne0625** [comment]
> > ![image](https://user-images.githubusercontent.com/24985105/279556527-461e677c-4731-4699-8878-ab7d5f5b9274.png)
> > ![image](https://user-images.githubusercontent.com/24985105/279556341-b1b52cc1-3b4f-4703-a50c-26238436e810.png) 可以跳转debug但是页面出来的是空白， 页面元素是有的，这是什么原因
> 
> 推荐用ScreenPreview进行页面预览，左边这个的预览原理是通过dom-to-image转成png图片进行显示的，更多的是作为实时预览的一个补充能力

嗯， 定位到是dom-to-image生成图片加载失败，可能是部分标签或者属性不支持， 具体报错原因没看到堆栈
