### ISSUE TITLE
补充几个小问题

### ISSUE THREAD

**Issue by chenyulun** [Nice-PLQ/devtools-remote-debugger#17]
1. 鼠标上去没有元素不显示块范围及尺寸， 我使用的是Google Chrome Canray的121.0.6126.0， 应该是使用了`<script type="module" src="./entrypoints/inspector/inspector.js"></script>`的原因，如果使用`<script type="module" src="./entrypoints/devtools_app/devtools_app.js"></script>`的原生页面就有范围和尺寸的显示，
2. 直接修改元素的内容，页面反应，
`src/client/sdk/domain/protocol.js`补充 `DOM.setNodeValue`数组属性
`src/client/sdk/domain/dom.js` 添加
```ts
export default class Dom extends BaseDomain {
// ...

  /**
   * @public
   */
  setNodeValue(params) {
    const { nodeId, value } = params;
    // const node = getNode(nodeId)
    const node = nodes.getNodeById(nodeId);
    node.nodeValue = value;
  }
//...
}
```
3. 修改之后调试器的展示不变，`page.js`缺少了监听参数
```js
    this.observerInst.observe(document.body, {
      childList: true,
      subtree: true,
      attributes: true, 
      characterData: true, // 其他几个监听地方都添加了，早就这个Page.js没有添加
    });
```

**Comment by chenyulun** [comment]
第一个问题我也在看看，暂时发生原生的devtools_app调试器发送了进入触发了`Overlay.highlightNode`，和移除触发了`Overlay.hideHighlight`, 使用inspector.js的时候，不发送`Overlay.highlightNode`，但是发送这个，实现这个
`{"id":82,"method":"DOM.getBoxModel","params":{"nodeId":76}}`,返回格式https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-getBoxModel

**Comment by chenyulun** [comment]
![image](https://github.com/Nice-PLQ/devtools-remote-debugger/assets/15979948/2d583799-5272-4a0c-b226-e99fdf3f082c)
还需要修补滚动之后重新截图上传，道路艰难，但是还算继续前行了

**Comment by chenyulun** [comment]
<img width="1094" alt="image" src="https://github.com/Nice-PLQ/devtools-remote-debugger/assets/15979948/3004e560-30c4-4418-8ec6-acd48c52d4f5">
我很想提合并，但是我的代码格式化使用了prettier,一格式化就整个文件格式了，要不我把perttier也配置上

**Comment by Nice-PLQ** [comment]
> <img alt="image" width="1094" src="https://user-images.githubusercontent.com/15979948/282700117-3004e560-30c4-4418-8ec6-acd48c52d4f5.png"> 我很想提合并，但是我的代码格式化使用了prettier,一格式化就整个文件格式了，要不我把perttier也配置上

最近有点点忙，perttier和eslint我抽空都补充下

**Comment by Nice-PLQ** [comment]
> 1. 鼠标上去没有元素不显示块范围及尺寸， 我使用的是Google Chrome Canray的121.0.6126.0， 应该是使用了`<script type="module" src="./entrypoints/inspector/inspector.js"></script>`的原因，如果使用`<script type="module" src="./entrypoints/devtools_app/devtools_app.js"></script>`的原生页面就有范围和尺寸的显示，
> 2. 直接修改元素的内容，页面反应，
>    `src/client/sdk/domain/protocol.js`补充 `DOM.setNodeValue`数组属性
>    `src/client/sdk/domain/dom.js` 添加
> 
> ```ts
> export default class Dom extends BaseDomain {
> // ...
> 
>   /**
>    * @public
>    */
>   setNodeValue(params) {
>     const { nodeId, value } = params;
>     // const node = getNode(nodeId)
>     const node = nodes.getNodeById(nodeId);
>     node.nodeValue = value;
>   }
> //...
> }
> ```
> 
> 3. 修改之后调试器的展示不变，`page.js`缺少了监听参数
> 
> ```js
>     this.observerInst.observe(document.body, {
>       childList: true,
>       subtree: true,
>       attributes: true, 
>       characterData: true, // 其他几个监听地方都添加了，早就这个Page.js没有添加
>     });
> ```

第1点是inspector.js，第2、3点我看看

**Comment by Nice-PLQ** [comment]
> ![image](https://user-images.githubusercontent.com/15979948/282696348-2d583799-5272-4a0c-b226-e99fdf3f082c.png) 还需要修补滚动之后重新截图上传，道路艰难，但是还算继续前行了

建议用ScreenPreview哈，可以实时同步页面预览以及滚动

**Comment by Nice-PLQ** [comment]
setNodeValue、getBoxModel协议已实现

**Comment by chenyulun** [comment]
你真棒，我可以把这个项目fork到内网部署吗？

**Comment by chenyulun** [comment]
> > ![image](https://user-images.githubusercontent.com/15979948/282696348-2d583799-5272-4a0c-b226-e99fdf3f082c.png) 还需要修补滚动之后重新截图上传，道路艰难，但是还算继续前行了
> 
> 建议用ScreenPreview哈，可以实时同步页面预览以及滚动

其实有些设备兼容性问题，还真同步展示复现不了，但是dom生成图形的库都有缺陷，挺难的

**Comment by Nice-PLQ** [comment]
> 你真棒，我可以把这个项目fork到内网部署吗？

当然可以哈，MIT开源协议
