### ISSUE TITLE
请教一下如何部署本项目

### ISSUE THREAD

**Issue by weilu114** [Nice-PLQ/devtools-remote-debugger#18]
如题，请教一下如何部署本项目，npm run start是什么时候执行？

**Comment by Nice-PLQ** [comment]
跟部署node服务是一样的，但是得先`npm run build`构建出管理后端产物

**Comment by weilu114** [comment]
谢谢大佬！！还想问个问题，能否在本地启动服务并调试移动端的H5页面？我试了下，在同个局域网下在浏览器的调试管理端没看到我移动端H5的页面，必须要把手机连接USB到电脑上才能看得到连接记录，是不是说明本地启动的服务无法远程调试？

**Comment by Nice-PLQ** [comment]
> 谢谢大佬！！还想问个问题，能否在本地启动服务并调试移动端的H5页面？我试了下，在同个局域网下在浏览器的调试管理端没看到我移动端H5的页面，必须要把手机连接USB到电脑上才能看得到连接记录，是不是说明本地启动的服务无法远程调试？

可以的，把`.env`改成你本机的ip和端口后，然后构建下sdk.js，接着在你H5页面中加载下sdk.js试下

**Comment by weilu114** [comment]
感谢大佬，已经可以了，现在在研究怎么部署node项目，不知道公司给不给部署：）
