### ISSUE TITLE
和chii的区别

### ISSUE THREAD

**Issue by godkun** [Nice-PLQ/devtools-remote-debugger#19]
作者有了解过 chii 么，你这个和chii相比，有哪些区别或者说是有哪些优势

chii地址：https://github.com/liriliri/chii

**Comment by Nice-PLQ** [comment]
看了下，是同类工具，建议你可以两个都试下看看有哪些区别~

**Comment by Nice-PLQ** [comment]
> 作者有了解过 chii 么，你这个和chii相比，有哪些区别或者说是有哪些优势
> 
> chii地址：https://github.com/liriliri/chii

看了下，是同类工具，建议你可以两个都试下看看有哪些区别~

**Comment by godkun** [comment]
> > 作者有了解过 chii 么，你这个和chii相比，有哪些区别或者说是有哪些优势
> > chii地址：https://github.com/liriliri/chii
> 
> 看了下，是同类工具，建议你可以两个都试下看看有哪些区别~

好嘞，感谢作者解答
