### ISSUE TITLE
webview背景黑色

### ISSUE THREAD

**Issue by cnguu** [Nice-PLQ/devtools-remote-debugger#2]
我尝试在安卓的webview上调试，但是页面背景色永远是黑色，这是什么原因
我这是一个spa的vue3应用
![image](https://github.com/Nice-PLQ/devtools-remote-debugger/assets/10758182/45687425-6021-490a-9a9f-dd2748e46601)

**Comment by Nice-PLQ** [comment]
请问是什么安卓版本呢，另外这个webview是系统自带的吗，还是某个app内的webview？

这个模式的页面预览是通过html2canvas截图实现的，可能会有一些不符合预期的问题。实时预览比较建议用screenshot这个功能

<img width="2040" alt="image" src="https://github.com/Nice-PLQ/devtools-remote-debugger/assets/10710341/789150dd-6c4f-478c-b234-1d7018b6476c">

**Comment by cnguu** [comment]
@Nice-PLQ 安卓13，app内置的webview加载本地的项目，尝试了浏览器打开也是同样的
1、screenshot作用不大，它并不会实时更新，只是个截图
2、黑背景很可能是没有设置css的background，默认给了黑色
3、选取元素无效
![image](https://github.com/Nice-PLQ/devtools-remote-debugger/assets/10758182/7a31d739-5ae5-4cf8-af0a-abc9522c0c0a)

**Comment by Nice-PLQ** [comment]
> @Nice-PLQ 安卓13，app内置的webview加载本地的项目，尝试了浏览器打开也是同样的 1、screenshot作用不大，它并不会实时更新，只是个截图 2、黑背景很可能是没有设置css的background，默认给了黑色 3、选取元素无效 ![image](https://user-images.githubusercontent.com/10758182/254765505-7a31d739-5ae5-4cf8-af0a-abc9522c0c0a.png)

1、screenshot是支持实时预览的哈
2、测试了下，确实是如果没有设置body、html背景色的话，默认是黑色，这个应该是html2canvas的原因。
3、是指元素高亮吗？在Element中选中标签的时候，在页面中会高亮的，可以看下真机上有没有高亮

**Comment by cnguu** [comment]
@Nice-PLQ 
1、screenshot试了，确实没有实时更新
2、黑背景手动设置body颜色解决了
3、元素选取如下图，看起来只有client端到server端，server端无法直接选取
![20230720_161301](https://github.com/Nice-PLQ/devtools-remote-debugger/assets/10758182/adf62947-b5f1-46bf-a7a7-26a61c9b75e3)

**Comment by Nice-PLQ** [comment]
@cnguu 
1、收到，我定位下看看
3、左边这个预览是不能元素选取的哈，因为它只是个图片。当激活元素审查的时候，你可以在真机上的页面中点击下试试看

**Comment by Nice-PLQ** [comment]
> @Nice-PLQ 1、screenshot试了，确实没有实时更新 2、黑背景手动设置body颜色解决了 3、元素选取如下图，看起来只有client端到server端，server端无法直接选取 ![20230720_161301](https://user-images.githubusercontent.com/10758182/254818756-adf62947-b5f1-46bf-a7a7-26a61c9b75e3.gif)

1、实时预览已修复，同时调整Screenshot命名为ScreenPreview
