### ISSUE TITLE
控制其他浏览器

### ISSUE THREAD

**Issue by ponull** [Nice-PLQ/devtools-remote-debugger#23]
理论上是不是也可以，我用A浏览器(已设置允许跨域)打开一个网页，连接到B浏览器，控制B浏览器，脱离node转发那一层的依赖，这样就可以做我的网页控制本机多个浏览器的自动化操作了

**Comment by Nice-PLQ** [comment]
你的场景应该更适合用puppeteer或者playwright

**Comment by ponull** [comment]
puppeteer和playwright 不方便抽离出纯浏览器端代码，那两个运行都必须是node环境

**Comment by Nice-PLQ** [comment]
> 理论上是不是也可以，我用A浏览器(已设置允许跨域)打开一个网页，连接到B浏览器，控制B浏览器，脱离node转发那一层的依赖，这样就可以做我的网页控制本机多个浏览器的自动化操作了

不能实现这种场景
