### ISSUE TITLE
关于安卓的问题

### ISSUE THREAD

**Issue by nonameShijian** [Nice-PLQ/devtools-remote-debugger#25]
如果我能获取到安卓Webview的调试端口，那这个端口应该怎么使用？如果直接用这个端口进行调试的话，直接与devtools交互而不用sdk是否可行
![79ed0bc0cb3dc2bfae6d55cacb3801a](https://github.com/Nice-PLQ/devtools-remote-debugger/assets/88574031/65905b79-920f-402d-9b8f-af67125cc015)

**Comment by Nice-PLQ** [comment]
这种考虑直接用chrome://inspect/#devices来调试吧

**Comment by nonameShijian** [comment]
> 这种考虑直接用chrome://inspect/#devices来调试吧

如果能在安卓上直接调试就更好了每次都得连接电脑挺麻烦的，这种原生提供的套接字如果能转成http端口调试起来应该会和官方一样的效果。

**Comment by Nice-PLQ** [comment]
这个倒是没有研究过

**Comment by nonameShijian** [comment]
> 这个倒是没有研究过

ok，那这个devtools的页面部分是如何编译的，想了解一下

**Comment by nonameShijian** [comment]
目前我的项目是在安卓app中显示网页+控制台的，但安卓设备初次使用会自动持续打印webview的页面情况，有什么配置可以默认关闭吗？（以下图片中的这个按钮的功能）
![image](https://github.com/Nice-PLQ/devtools-remote-debugger/assets/88574031/7235bf60-964d-49b6-a5cb-7cc5c3a32625)
