### ISSUE TITLE
在移动端，网络请求的文件列表table标签高度不对，且在最底端时继续向下滚动的动画显示也有问题

### ISSUE THREAD

**Issue by nonameShijian** [Nice-PLQ/devtools-remote-debugger#26]
导致最后一个文件的请求看不到
![image](https://github.com/Nice-PLQ/devtools-remote-debugger/assets/88574031/67c0c33a-fc6d-4279-8706-d9dd849639a7)

**Comment by Nice-PLQ** [comment]
devtools-frontend本身的问题不考虑处理哈，我会不定期同步chrome官方最新的devtools-frontend代码并编译
