### ISSUE TITLE
请问sdk里发送CDP的数据是作者自己看官方文档写的吗？

### ISSUE THREAD

**Issue by wwereal** [Nice-PLQ/devtools-remote-debugger#31]
https://chromedevtools.github.io/devtools-protocol/ 这个官方文档比较简略，很多细节没有介绍得很清楚，一些方法/时间发送的时机也没说，请教作者是通过什么途径知道各种协议发送的细节呀？

**Comment by Nice-PLQ** [comment]
<img width="1224" alt="image" src="https://github.com/user-attachments/assets/d0843b80-b59a-4e8e-a5cd-93ea4ff4c832">

在本地的Devtools中查看Protocol Monitor面板，可以看到协议的发送时间和细节，然后再去CDP官网找到对应的协议研究，我是这样做的。
