### ISSUE TITLE
sdk.js 放到remote html 中，wws连接失败

### ISSUE THREAD

**Issue by wsdmzy** [Nice-PLQ/devtools-remote-debugger#7]
WebSocket connection to 'wss://localhost:8080/remote/debug/client/KTzC7tGi?favicon=&time=1691642483080&title=&ua=Mozilla%2F5.0%20%28iPhone%3B%20CPU%20iPhone%20OS%2016_0_3%20like%20Mac%20OS%20X%29%20AppleWebKit%2F605.1.15%20%28KHTML%2C%20like%20Gecko%29%20Mobile%2F15E148&url=xxxxindex.html' failed: Could not connect to the server.

**Comment by wsdmzy** [comment]
代理 远程html地址 加上  sdk.js。   看远程的html webview 控制台报错 wss connect 失败， 本地服务是启动了的

**Comment by lsdlh** [comment]
> > 代理远程html地址加上sdk.js。看远程的html webview控制台报错wss连接失败，本地服务是启动了的
> 
> 看起来是代理的远程html的页面是https协议的，你在sdk.js里搜下wss，改成ws试下呢。
ws可以
