### ISSUE TITLE
给个建议，sdkjs的DEBUG_HOST能不能动态改变，比如放到window修改重连

### ISSUE THREAD

**Issue by CodeInn1024** [Nice-PLQ/devtools-remote-debugger#8]

**Comment by Nice-PLQ** [comment]
在什么场景下会需要动态更改DEBUG_HOST呢

**Comment by lsdlh** [comment]
> 在什么场景下会需要动态更改DEBUG_HOST呢

局域网本地调试，不同wifi的ip地址不一样，动态修改更方便

**Comment by Nice-PLQ** [comment]
这种场景似乎比较小众，可能暂时不会支持。一般来说，如果只是本地把这个项目跑起来的话，手动改DEBUG_HOST应该也还好。如果是把该项目部署到正式环境，理论上DEBUG_HOST是固定的。
